### ISSUE TITLE
DynamicsTransform internal const cannot be set outside of test project

### ISSUE THREAD

**Issue by ndumais** [cmdwtf/UnityTools#2]
I've stumbled upon this while trying to set the "Space" internal const in my own project.

For some reason, theses fields can be set just fine in your test project

![image](https://github.com/cmdwtf/UnityTools/assets/48096495/e6c91170-4a6d-463b-aec4-e6e8261a8205)

A work around I found was just redefining them in the code, then it will stay for that prefab or gameObject, even if changed later

![image](https://github.com/cmdwtf/UnityTools/assets/48096495/cb293e61-6b96-4068-8417-5fd13e1484a5)

Any idea what causes this?
Never used internal const for variables I wanted to define in editor in my projects before

**Comment by nitz** [comment]
`internal` just limits the access for the member to only being used within the assembly they're defined in. I just needed fixed values so that when `Reset()` was called by Unity (e.g.: when adding a component, etc.) I was putting everything in a known state, but it shouldn't matter what the values are.

You can edit your local copy directly to either make them `public static` which would let you adjust them, or you can make them `internal static` and add a line to `AssemblyInfo.cs` so that your assembly can modify internals like so:

```csharp
[assembly: InternalsVisibleTo("Your.Assembly.Name")]
```

If I ever get back to working on this, I'll keep in mind that defaults like that would make a nice candidate for a project wide setting.
